# Generated by Django 2.1 on 2018-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_planned_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='planned_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
