# Generated by Django 2.1 on 2018-09-08 09:04

from django.db import migrations
from django.utils import timezone


def refresh_history(category, PlannedAmountHistory):
    now = timezone.now()
    year = now.year
    month = now.month

    PlannedAmountHistory.objects.update_or_create(
        year=year,
        month=month,
        category=category,
        defaults={
            'amount': category.planned_amount,
        },
    )


def migrate_history(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    PlannedAmountHistory = apps.get_model('category', 'PlannedAmountHistory')

    for category in Category.objects.all():
        refresh_history(category, PlannedAmountHistory)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20180908_0907'),
    ]

    operations = [
        migrations.RunPython(migrate_history),
    ]
