# Generated by Django 2.1 on 2018-09-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_plannedamounthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedamounthistory',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
