# Generated by Django 2.1 on 2018-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activityfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfile',
            name='key',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
