sudo: required

services:
    - docker

before_install:
    - sudo pip install --upgrade awscli
    - sudo pip install --upgrade awsebcli

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
    - ./deploy/scripts/build_client.sh
    - ./deploy/scripts/build_server.sh

script:
    - echo 'TODO run test here'

after_success:
    - ./deploy/travis/deploy_client.sh
    - ./deploy/travis/deploy_server.sh
    - docker push devtc/pennyworth:client-latest
    - docker push devtc/pennyworth:server-latest

env:
  global:
    - PENNYWORTH_API_DOMAIN=https://pennyworth-api.togglecorp.com
